// ===========================DATABASE===========================

export const FETCH_NOTIFICATIONS__REQUEST = 'FETCH_NOTIFICATIONS__REQUEST';
export const FETCH_NOTIFICATIONS__SUCCESS = 'FETCH_NOTIFICATIONS__SUCCESS';
export const FETCH_NOTIFICATIONS__FAILURE = 'FETCH_NOTIFICATIONS__FAILURE';
